# Generated by Django 6.0.5 on 2026-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=200)),
                ('cover_note', models.TextField(blank=True)),
                ('resume', models.FileField(help_text='PDF, DOC, DOCX — max 5 MB', upload_to='resumes/%Y/%m/')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=25)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
